New Interface
phantamanta44/ae2-fluid-crafting pull request #9
Opened 2020-10-26 13:08 UTC by Yefancy

Dual Interface for fluid and item input and visible in interface terminal.

2020-10-26 13:12 UTC, Yefancy commented
Hi friend, I implemented the new interface I mentioned in the issue and requested to merge, although you did not respond to my idea later. I added a new interface to perform your composition tasks, and accept fluid input. Also making a slight hack of the interface terminal to show (part) dual interface. 
I like the work you are doing. I hope you will agree it.

2020-10-26 13:57 UTC, phantamanta44 commented
oh sorry, i missed your last comment on the other issue. i'm a little busy right now, so i'll have to review this later, but it looks okay at a quick glance

2020-10-30 19:01 UTC, phantamanta44 requested changes
needs some significant work. major points are:
* the dual interface should function as a combination item/fluid interface rather than just an item interface with a fluid tank hacked in. see my comment on `TileDualInterface`
* the fluid interface should be visible to the player. this might be implemented as a set of tabs at the top of the dual interface GUI that lets you swap between the item and fluid interface GUIs
* the dual interface textures should probably be a little more different from the textures for standard item interfaces

2020-10-30 19:01 UTC, phantamanta44 commented on src/main/java/xyz/phanta/ae2fc/coremod/ContainerInterfaceTerminalTransformer.java
> +            System.out.println("[ae2fc] Transforming ContainerInterfaceTerminalTransformer...");
this is probably meant to say `"Transforming ContainerInterfaceTerminal..."`

2020-10-30 19:01 UTC, phantamanta44 commented on src/main/java/xyz/phanta/ae2fc/handler/CoreModHooks.java
> +    }
please don't break abstractions like this. ideally, you should write a util class implementing `IMachineSet` that wraps the two machine sets you retrieve and delegates calls to them

2020-10-30 19:01 UTC, phantamanta44 commented on src/main/java/xyz/phanta/ae2fc/coremod/ContainerInterfaceTerminalTransformer.java
> +    }
i'm a little concerned that this may conflict with any other mod that tries to hack `ContainerInterfaceTerminal` for the same reason, but we can probably just deal with that later if it ever comes up

2020-10-30 19:01 UTC, phantamanta44 commented on src/main/java/xyz/phanta/ae2fc/init/FcBlocks.java
> +    public static BlockDualInterface Dial_Interface;
this should be `DUAL_INTERFACE`

2020-10-30 19:01 UTC, phantamanta44 commented on src/main/resources/assets/ae2fc/lang/en_us.lang
> +tile.ae2fc:part_dual_interface.name=Part Dual Interface
these should probably both be "ME Dual Interface"

2020-10-30 19:01 UTC, phantamanta44 commented on src/main/resources/assets/ae2fc/lang/en_us.lang
> +item.ae2fc:part_dual_interface.name=Part Dual Interface
as above

2020-10-30 19:01 UTC, phantamanta44 commented on src/main/java/xyz/phanta/ae2fc/constant/NameConst.java
> +    public static final String BlOCK_DUAL_INTERFACE = "dual_interface";
this should be `BLOCK_DUAL_INTERFACE`

2020-10-30 19:01 UTC, phantamanta44 commented on src/main/java/xyz/phanta/ae2fc/parts/PartDualInterface.java
> +        }
see comment for TileDualInterface

2020-10-30 19:01 UTC, phantamanta44 commented on src/main/java/xyz/phanta/ae2fc/tile/TileDualInterface.java
> +        }
this is a pretty bad hack...

ideally, the behaviour i would want out of the dual interface is for it to act like both an item and fluid interface, not just an item interface with a fluid tank hacked in. i would suggest something along the lines of maintaining both a `DualityInterface` and a `DualityFluidInterface` instance rather than using the weird amalgam of `DualityDInterface`

2020-10-30 22:47 UTC, Yefancy commented
You're right. It's really simple. I will reimplement it and add gui so that it has a complete fluid interface features rather than simply receiving fluid input， change textures and anything else you mentioned. However, i really busy for my real stuff this week，It may take some time.

2020-10-30 22:50 UTC, phantamanta44 commented
no pressure! thanks for all your hard work

2020-11-05 08:33 UTC, closed without merging